numpy是Python中使用最广泛的包之一，它很像R中的array数组，或者matrix及一维的向量。
# numpy数组的生成
## 在humpy中生成随机数
numpy中有一个包叫做randam,包括很多生成随机数的函数。

In [3]:
import numpy as np #导入numpy
np.random.seed(523) #随机种子设定值为523
np.random.rand(2,3,4) #产生2*3*4个[0,1)之间的随机数，并形成2*3*4之间的三维数组
np.random.randn(3,5) #产生3*5个标准正态分布随机数并形成3*5的二维数组
np.random.normal(3,5,100) #产生100个均值为3，标准差为5的N（3，5）随机数
np.random.uniform(3,7,100) #产生100个上下界分别为3和7的均匀分布随机数
np.random.randint(3,30,34) #产生34个[3,30)中的随机整数
x = [2,5,-7.6]
# 从数组中按照给定概率p随机放回抽取20个样本
np.random.choice(x,20,replace=True,p=[0.1,0.3,0.6])
# 从数组x中完全随机（不放回）抽取2个样本
np.random.choice(x,2,replace=False)
# 把0-9的自然数随机排列
np.random.permutation(range(10))

(array([-7.6,  5. ,  2. , -7.6,  5. ,  5. , -7.6, -7.6,  5. ,  2. , -7.6,
        -7.6, -7.6, -7.6,  2. , -7.6, -7.6, -7.6, -7.6,  5. ]),
 array([-7.6,  5. ]),
 array([9, 0, 3, 7, 2, 4, 6, 1, 8, 5]))

## 从基本数组中生成数据
使用np.array生成数据,跟list和tuple很相近。

In [9]:
x0 = [[1,3,-5],[3,4],'I am super nice person',(2,6),{2:0,'I':(5,23)}]
x = np.array([[1,3,-5],[3,4],'I am super nice person',(2,6),{2:0,'I':(5,23)}])
# 输出数组，以及数组的长度形状
x0,len(x0),x,x.shape,x.size
# 规则的数组
y = np.array(((2,1,-7),[5.5,1,3],(0.89,2,-88)))
y,y.shape,y.size,y.ndim

(array([[  2.  ,   1.  ,  -7.  ],
        [  5.5 ,   1.  ,   3.  ],
        [  0.89,   2.  , -88.  ]]),
 (3, 3),
 9,
 2)

## 直接产生需要的数组
使用np.arange函数，此函数的用法有三种：
1. 输入一个参数，输出从0开始步长为1小于该数的所有整数增数列；
2. 输入两个参数，输出为第一个数字开始到小于该数的步长为1的升序列；
3. 输入三个参数，从第一个参数开始，逐次增加第三个参数的值，直到不超过第二个参数的绝对值。

In [10]:
x1 = np.arange(10.5)
x2 = np.arange(2.3,10)
x3 = np.arange(2.3,10.5,0.8)
x1,x2,x3

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 array([2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3, 9.3]),
 array([ 2.3,  3.1,  3.9,  4.7,  5.5,  6.3,  7.1,  7.9,  8.7,  9.5, 10.3]))

## 产生特殊值的数组

In [16]:
# 全为0的数组
x1 = np.zeros([2,3,4])
# 全为1的数组
x2 = np.ones([2,3,4])
# 指定数字的数组
x3 = np.full([2,3,4],888)
# 单位矩阵
x4 = np.identity(2)
# 任意值的空数组
x5 = np.empty((2,3))
# 根据函数关系确定数组,x_{ij}的值为i^2+i*j,这里实际上是传入i**2 + i*j的返回值，也可以逻辑逻辑表达式的形式
x6 = np.fromfunction(lambda i,j: i**2 + i*j,(3,4))
x1,x2,x3,x4,x5,x6

(array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]),
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]),
 array([[[888, 888, 888, 888],
         [888, 888, 888, 888],
         [888, 888, 888, 888]],
 
        [[888, 888, 888, 888],
         [888, 888, 888, 888],
         [888, 888, 888, 888]]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
        [3.33773471e-307, 2.67017691e-306, 2.42092166e-322]]),
 array([[ 0.,  0.,  0.,  0.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  6.,  8., 10.]]))

# 数据的存取

In [32]:
import os
m = os.getcwd()
print(m)
##创建文件夹Data
os.makedirs('/Data', exist_ok=True)
x = np.random.randn(5,3)
print(x)
# 存入数据
np.savetxt('/Data/commas1.csv',x,delimiter=',')
# 导入数据
x2 = np.loadtxt('/Data/commas1.csv',delimiter=',')
x2

C:\Users\Ling Wanying\PycharmProjects\DeepLearning_2022\OpenDataScience\Numpy
[[ 1.27930963 -1.01390266 -0.71406178]
 [ 0.21528265  0.86804909  0.57923798]
 [-0.31959123 -1.36876801  0.66276592]
 [ 0.08968844  0.46906647 -0.75589987]
 [-0.34800369  0.09850096  0.43314466]]


array([[ 1.27930963, -1.01390266, -0.71406178],
       [ 0.21528265,  0.86804909,  0.57923798],
       [-0.31959123, -1.36876801,  0.66276592],
       [ 0.08968844,  0.46906647, -0.75589987],
       [-0.34800369,  0.09850096,  0.43314466]])

# 数组的运算
## 改变形状
使用reshape函数

In [33]:
x = np.arange(16).reshape(2,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

## 同维数组之间的运算规则
1. 如果两个数组都是整型的，除了除法为浮点型，其他运算结果（加、减和乘积）为整型；
2. 浮点型元素之间运算，还为浮点型。
## 四舍五入和取整计算
round为四舍五入，大于对象的最小整数为ceil,小于对象的最大整数为floor

In [34]:
np.round(5.88),np.ceil(5.1),np.floor(5.1)

(6.0, 6.0, 5.0)

## 一些常用命令整理
### 求最大值，最小数，求和，求积

In [44]:
import numpy as np
x = np.array([-2,7,-1,9,-5,0.88]).reshape(2,3)
# 输出x的最大值，以及逐行排序（从0开始）对应的位置
x,np.max(x),np.argmax(x)
# 类似的，还有最小值
np.min(x),np.argmin(x)
# 求各个元素的和，累计和，乘积，累计乘积和差分
np.sum(x),np.cumsum(x),np.prod(x),np.cumprod(x),np.diff(x)

(8.88,
 array([-2.  ,  5.  ,  4.  , 13.  ,  8.  ,  8.88]),
 -554.4,
 array([  -2. ,  -14. ,   14. ,  126. , -630. , -554.4]),
 array([[  9.  ,  -8.  ],
        [-14.  ,   5.88]]))

对矩阵做差分的时候，需要注明对哪一维进行计算。

In [52]:
x=np.arange(3.9).reshape(2,2)
# axis为0表示按列运算，为1表示按行运算
x,np.diff(x,axis=0),np.diff(x,axis=1),np.sum(x,axis=0),np.sum(x,axis=1)

(array([[0., 1.],
        [2., 3.]]),
 array([[2., 2.]]),
 array([[1.],
        [1.]]),
 array([2., 4.]),
 array([1., 5.]))

### 符号函数、指数、对数、绝对值、平方值

In [56]:
x,np.sign(x),np.exp(x),np.log(np.exp(x)),abs(x),x**2

(array([[0., 1.],
        [2., 3.]]),
 array([[0., 1.],
        [1., 1.]]),
 array([[ 1.        ,  2.71828183],
        [ 7.3890561 , 20.08553692]]),
 array([[0., 1.],
        [2., 3.]]),
 array([[0., 1.],
        [2., 3.]]),
 array([[0., 1.],
        [4., 9.]]))

### 矩阵之间的内积和外积运算

In [59]:
#内积
x = np.random.randn(2,3)
y = np.random.randn(3,6)
x,y,np.dot(x,y)
#外积
np.outer(x,y)

array([[ 3.21253368e-02, -2.02979420e+00,  1.72069893e+00,
         1.34101546e+00,  1.17732257e+00,  1.63185275e-01,
         1.40990814e+00,  2.73237011e-01,  7.59503027e-01,
         8.60412760e-01, -1.59938267e+00, -1.91757556e+00,
         3.33776350e-01, -8.87501312e-01,  2.22848436e-01,
         5.68550743e-01,  5.05776673e-01,  1.65312947e+00],
       [ 1.03182715e-02, -6.51945468e-01,  5.52667785e-01,
         4.30718026e-01,  3.78141840e-01,  5.24131461e-02,
         4.52845525e-01,  8.77604391e-02,  2.43943231e-01,
         2.76354223e-01, -5.13702464e-01, -6.15902190e-01,
         1.07204946e-01, -2.85054739e-01,  7.15762355e-02,
         1.82611656e-01,  1.62449380e-01,  5.30965287e-01],
       [-5.36218782e-03,  3.38802293e-01, -2.87209778e-01,
        -2.23835063e-01, -1.96512329e-01, -2.72380053e-02,
        -2.35334257e-01, -4.56072470e-02, -1.26772146e-01,
        -1.43615454e-01,  2.66960323e-01,  3.20071362e-01,
        -5.57121467e-02,  1.48136929e-01, -3.71966582e

### 合并和拆分矩阵

In [62]:
x1 = np.random.rand(2,2)
x2 = np.random.rand(2,2)
# 纵向叠加
z1 = np.concatenate((x1,x2),axis=0)
# 横向叠加
z2 = np.concatenate((x1,x2),axis=1)
# 按纵向拆分成4段
y1 = np.split(z1,4,axis=0)
# 按横向拆分成4段
y2 = np.split(z2,4,axis=1)
x1,x2,z1,z2,y1,y2

(array([[0.60039104, 0.63677104],
        [0.68080759, 0.44254223]]),
 array([[0.85051222, 0.14525866],
        [0.21475964, 0.90117376]]),
 array([[0.60039104, 0.63677104],
        [0.68080759, 0.44254223],
        [0.85051222, 0.14525866],
        [0.21475964, 0.90117376]]),
 array([[0.60039104, 0.63677104, 0.85051222, 0.14525866],
        [0.68080759, 0.44254223, 0.21475964, 0.90117376]]),
 [array([[0.60039104, 0.63677104]]),
  array([[0.68080759, 0.44254223]]),
  array([[0.85051222, 0.14525866]]),
  array([[0.21475964, 0.90117376]])],
 [array([[0.60039104],
         [0.68080759]]),
  array([[0.63677104],
         [0.44254223]]),
  array([[0.85051222],
         [0.21475964]]),
  array([[0.14525866],
         [0.90117376]])])

In [ ]:
### 向数组中插入值
下面的值也可以替换为数组。

In [66]:
x = np.array([[11,32,26],[47,54,89],[92,64,95]])
#下标1的位置插入0
x1 = np.insert(x,1,0)
#行号为1的位置插入一行0
x2 = np.insert(x,1,0,axis=0)
#列号为1的位置插入一行0
x3 = np.insert(x,1,0,axis=1)
x,x1,x2,x3

(array([[11, 32, 26],
        [47, 54, 89],
        [92, 64, 95]]),
 array([11,  0, 32, 26, 47, 54, 89, 92, 64, 95]),
 array([[11, 32, 26],
        [ 0,  0,  0],
        [47, 54, 89],
        [92, 64, 95]]),
 array([[11,  0, 32, 26],
        [47,  0, 54, 89],
        [92,  0, 64, 95]]))

### 部分数组的赋值
此例子中，x和y指向的是计算机同一个地址，修改y的值，x也会改变。z则只是得到了x的值，但是地址并不一样，修改z的值，x不会改变。

In [69]:
x = np.arange(12).reshape(2,6)
y=x
z=x.copy()
x,y,z

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]))

### 对角矩阵和上下三角矩阵

In [72]:
x = np.random.rand(3,3)
z = np.diag(x)
z2 = np.triu(x)
z3 = np.tril(x)
x,z,z2,z3

(array([[0.88813866, 0.33646691, 0.32398365],
        [0.69512365, 0.36455999, 0.92905659],
        [0.29576336, 0.15191326, 0.29152624]]),
 array([0.88813866, 0.36455999, 0.29152624]),
 array([[0.88813866, 0.33646691, 0.32398365],
        [0.        , 0.36455999, 0.92905659],
        [0.        , 0.        , 0.29152624]]),
 array([[0.88813866, 0.        , 0.        ],
        [0.69512365, 0.36455999, 0.        ],
        [0.29576336, 0.15191326, 0.29152624]]))